 #  Data Gathering and Model Training (model.ipynb)
- Select the kernel

- Load data and import libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error as mse, mean_absolute_error as mae, root_mean_squared_error as rmse

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/SagarChhabriya/data-science/refs/heads/main/datasets/TBD/salary_dataset.csv")
df

     Experience Years  Salary
0                 0.6   27868
1                 0.6   31381
2                 0.7   44204
3                 0.8   39551
4                 0.9   25984
..                ...     ...
195              14.6  158775
196              14.6  160741
197              14.6  170198
198              14.8  154396
199              14.8  173265

[200 rows x 2 columns]

- Preprocessing + train test split

In [3]:
df.isna().sum()

Experience Years    0
Salary              0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Experience Years  200 non-null    float64
 1   Salary            200 non-null    int64
dtypes: float64(1), int64(1)
memory usage: 3.3 KB

In [6]:
df.describe()

       Experience Years         Salary
count        200.000000     200.000000
mean           7.519000   96834.455000
std            4.279792   40938.012116
min            0.600000   25984.000000
25%            3.800000   60248.500000
50%            7.700000   94732.000000
75%           11.500000  132854.500000
max           14.800000  173265.000000

In [7]:
x = df['Experience Years']
y = df['Salary']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [9]:
x_train = x_train.values.reshape(-1,1)
x_test = x_test.values.reshape(-1,1)

- Model training

In [10]:
lr = LinearRegression()

lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)

- Model evaluation

In [11]:
r2_score(y_pred, y_test)

0.9821864088840995

In [12]:
mse(y_pred, y_test)

23745684.25481864

In [13]:
mae(y_pred, y_test)

4056.3438613897365

In [14]:
rmse(y_pred, y_test)

4872.95436617445

- Model serialization

In [15]:
import pickle

with open ("model.pkl", "wb") as file:
    pickle.dump(lr, file)

In [16]:
with open ("model.pkl", "rb") as file:
    model = pickle.load(file)

In [17]:
model.predict([[0.6]])

array([31417.94418739])

In [18]:
import sklearn as sk 
import streamlit as st

print(np.__version__)
print(pd.__version__)
print(sk.__version__)
print(st.__version__)

2.5.3
3.0.6
1.9.1
1.64.0